### ISSUE TITLE
Can't build image, no ./patches/usr/

### ISSUE THREAD

**Issue by Aljutor** [scaleway/image-voidlinux#11]
So, what i do on debian system:
```
git clone https://github.com/scaleway/image-voidlinux.git
cd image-voidlinux
make install

```
and i receive error:
```
Step 4 : ADD ./patches/usr/ /usr/
INFO[0010] patches/usr/: no such file or directory
```

I tried to fix it and  remove from Dockefile:
```
ADD ./patches/usr/ /usr/
RUN passwd -d root
```

Image build, and server starts, it refuse connection via ssh, but at least i can connect via serial console.
I found that some folders have ownership of user 1001, that's strange and prevent from root login via ssh key (Authentication refused: bad ownership or modes for directory)

**Comment by moul** [comment]
Hi @Aljutor,

We need some more work on this image.
The current source code only handle C1 servers, we need to add multiarch support to support C2 and VPS offers.

I will refactor the image tomorrow, stay tuned

**Comment by moul** [comment]
I just fixed the armhf build (for the C1 servers), I will now add the x86_64 support for C2 servers and VPS, but you can already build the image from a C1 server

**Comment by Aljutor** [comment]
Ok. I will try right now.

**Comment by moul** [comment]
@Aljutor, expected for this week

**Comment by Aljutor** [comment]
@moul  I created server from this volume. It is build well, but - still refuse ssh connection and cause no root password  - i can't login in serial console.

**Comment by moul** [comment]
@Aljutor, oh sorry, I just tested the build process, but I didn't ran the image, I think one script is not working or is not registered anymore, I will need to give more investigation.

As you already built the image by yourself, I suggest you to just edit the Dockerfile, remove the root password deletion and configure a root password instead, then rebuild the image and boot.
